
import React, { useRef, useEffect } from 'react';

const DisclaimerSection: React.FC = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('animate-reveal');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.1 }
    );
    
    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }
    
    return () => {
      if (sectionRef.current) {
        observer.unobserve(sectionRef.current);
      }
    };
  }, []);
  
  return (
    <section id="disclaimer" ref={sectionRef} className="py-20 relative opacity-0">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 neo-glow">Legal Disclaimer</h2>
          <p className="text-lg max-w-2xl mx-auto">
            Important information about the use of Neo-Matrix GPT.
          </p>
        </div>
        
        <div className="max-w-4xl mx-auto matrix-card">
          <div className="p-6">
            <div className="mb-6 p-4 border-2 border-matrix-green/40 rounded-lg bg-matrix-green/10">
              <p className="text-matrix-green text-center font-bold text-lg mb-2">
                ⚠️ IMPORTANT: THIS IS A SIMULATION ⚠️
              </p>
              <p className="text-matrix-green/90 text-center font-semibold">
                This is an AI-powered simulation for entertainment and personal exploration purposes only.
              </p>
              <p className="text-matrix-green/80 text-center mt-2 text-sm">
                AI responses may be inaccurate, incomplete, or misleading. Do not rely on this tool for factual information, professional advice, or critical decisions.
              </p>
            </div>
            
            <h3 className="text-xl font-bold mb-4">Terms of Use</h3>
            
            <p className="mb-4 text-matrix-green/80">
              <strong>Neo-Matrix GPT is a simulated AI experience</strong> designed strictly for entertainment and personal philosophical exploration purposes. This is not a factual information source. All content, conversations, and experiences are fictional and generated by artificial intelligence, which may produce inaccurate, misleading, or completely false information.
            </p>
            
            <p className="mb-4 text-matrix-green/80 font-semibold">
              The AI responses should NOT be taken as professional advice, therapy, medical guidance, legal counsel, financial recommendations, or factual information about reality.
            </p>
            
            <p className="mb-4 text-matrix-green/80">
              By using Neo-Matrix GPT, you acknowledge that:
            </p>
            
            <ul className="list-disc pl-6 mb-6 text-matrix-green/80 space-y-2">
              <li><strong>This is a simulation:</strong> All interactions are with an AI system that may generate false, inaccurate, or misleading information.</li>
              <li><strong>Entertainment only:</strong> This tool is for personal exploration and entertainment purposes exclusively, not for making real-world decisions.</li>
              <li><strong>AI limitations:</strong> The AI may produce responses that seem convincing but are factually incorrect, biased, or unreliable.</li>
              <li><strong>No professional advice:</strong> Responses do not constitute medical, legal, financial, therapeutic, or any other form of professional advice.</li>
              <li><strong>Fictional content:</strong> All philosophical perspectives, existential discussions, binary codes, puzzles, and challenges are part of a fictional experience.</li>
              <li><strong>No hidden meanings:</strong> There is no hidden information about real-world events, entities, or secret knowledge.</li>
              <li><strong>Generated images:</strong> All AI-generated images are fictional and do not depict real people or events.</li>
              <li><strong>No liability:</strong> We are not responsible for any interpretations, actions, decisions, or consequences resulting from interactions with this tool.</li>
            </ul>
            
            <h3 className="text-xl font-bold mb-4">Limitation of Liability</h3>
            
            <p className="mb-4 text-matrix-green/80">
              AI Web Tools LLC, its affiliates, partners, employees, or representatives shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from your access to or use of Neo-Matrix GPT.
            </p>
            
            <p className="mb-6 text-matrix-green/80">
              By using this service, you agree to indemnify and hold harmless AI Web Tools LLC and its representatives from any claims, losses, damages, liabilities, costs, and expenses arising from your use of Neo-Matrix GPT.
            </p>
            
            <h3 className="text-xl font-bold mb-4">Privacy Policy</h3>
            
            <p className="mb-4 text-matrix-green/80">
              For information on how your data is collected, used, and protected when interacting with Neo-Matrix GPT, please refer to our <a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noopener noreferrer" className="text-matrix-green hover:text-matrix-lightgreen underline">Privacy Policy</a>.
            </p>
            
            <h3 className="text-xl font-bold mb-4">Terms of Service</h3>
            
            <p className="mb-4 text-matrix-green/80">
              For complete information regarding the terms governing your use of Neo-Matrix GPT, please review our <a href="https://aiwebtools.lovable.app/disclaimers" target="_blank" rel="noopener noreferrer" className="text-matrix-green hover:text-matrix-lightgreen underline">Terms of Service</a>.
            </p>
            
            <p className="text-sm text-matrix-green/60 mt-8">
              By using Neo-Matrix GPT, you acknowledge that you have read, understood, and agree to these terms and conditions.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DisclaimerSection;
