
import React, { useRef, useEffect } from 'react';

const DisclaimerSection: React.FC = () => {
  const sectionRef = useRef<HTMLDivElement>(null);
  
  useEffect(() => {
    const observer = new IntersectionObserver(
      (entries) => {
        entries.forEach((entry) => {
          if (entry.isIntersecting) {
            entry.target.classList.add('animate-reveal');
            observer.unobserve(entry.target);
          }
        });
      },
      { threshold: 0.1 }
    );
    
    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }
    
    return () => {
      if (sectionRef.current) {
        observer.unobserve(sectionRef.current);
      }
    };
  }, []);
  
  return (
    <section id="disclaimer" ref={sectionRef} className="py-20 relative opacity-0">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold mb-4 neo-glow">Legal Disclaimer</h2>
          <p className="text-lg max-w-2xl mx-auto">
            Important information about the use of Neo-Matrix GPT.
          </p>
        </div>
        
        <div className="max-w-4xl mx-auto matrix-card">
          <div className="p-6">
            <div className="mb-6 p-4 border border-matrix-green/30 rounded-lg bg-matrix-green/5">
              <p className="text-matrix-green/90 text-center font-semibold">
                This content is provided for informational, educational, and research purposes only.
              </p>
            </div>
            
            <h3 className="text-xl font-bold mb-4">Terms of Use</h3>
            
            <p className="mb-4 text-matrix-green/80">
              Neo-Matrix GPT is designed for entertainment and philosophical exploration purposes only. The content, conversations, and experiences provided by Neo-Matrix GPT are fictional and should not be taken as professional advice, therapy, or factual information about reality.
            </p>
            
            <p className="mb-4 text-matrix-green/80">
              By using Neo-Matrix GPT, you acknowledge that:
            </p>
            
            <ul className="list-disc pl-6 mb-6 text-matrix-green/80 space-y-2">
              <li>The AI's responses are generated for entertainment and do not represent medical, legal, financial, or psychological advice.</li>
              <li>Any philosophical perspectives or existential discussions are meant to provoke thought, not to replace professional guidance.</li>
              <li>The binary codes, puzzles, and challenges are part of the fictional experience and do not contain hidden information about real-world events or entities.</li>
              <li>Images generated by the AI are fictional representations and do not depict real people or events.</li>
              <li>We are not responsible for any interpretations, actions, or decisions made based on interactions with Neo-Matrix GPT.</li>
            </ul>
            
            <h3 className="text-xl font-bold mb-4">Limitation of Liability</h3>
            
            <p className="mb-4 text-matrix-green/80">
              AI Web Tools LLC, its affiliates, partners, employees, or representatives shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from your access to or use of Neo-Matrix GPT.
            </p>
            
            <p className="mb-6 text-matrix-green/80">
              By using this service, you agree to indemnify and hold harmless AI Web Tools LLC and its representatives from any claims, losses, damages, liabilities, costs, and expenses arising from your use of Neo-Matrix GPT.
            </p>
            
            <h3 className="text-xl font-bold mb-4">Privacy Policy</h3>
            
            <p className="mb-4 text-matrix-green/80">
              For information on how your data is collected, used, and protected when interacting with Neo-Matrix GPT, please refer to our <a href="https://openai.com/policies/privacy-policy/" target="_blank" rel="noopener noreferrer" className="text-matrix-green hover:text-matrix-lightgreen underline">Privacy Policy</a>.
            </p>
            
            <h3 className="text-xl font-bold mb-4">Terms of Service</h3>
            
            <p className="mb-4 text-matrix-green/80">
              For complete information regarding the terms governing your use of Neo-Matrix GPT, please review our <a href="https://aiwebtools.lovable.app/disclaimers" target="_blank" rel="noopener noreferrer" className="text-matrix-green hover:text-matrix-lightgreen underline">Terms of Service</a>.
            </p>
            
            <p className="text-sm text-matrix-green/60 mt-8">
              By using Neo-Matrix GPT, you acknowledge that you have read, understood, and agree to these terms and conditions.
            </p>
          </div>
        </div>
      </div>
    </section>
  );
};

export default DisclaimerSection;
